#
# Module manifest for module 'NitroModule'
#
# Generated by: Esther Barthel, MSc
#
# Generated on: 5/12/2017
#
@{
	
	# Script module or binary module file associated with this manifest.
	RootModule = 'NitroModule.psm1'
	
	# Version number of this module.
	ModuleVersion = '0.0.1'
	
	# ID used to uniquely identify this module
	GUID = 'd288d2ed-5569-47b7-a01d-affe0706be92' # execute [guid]::NewGuid() for your own GUI
	
	# Author of this module
	Author = 'Esther Barthel, MSc'
	
	# Company or vendor of this module
	CompanyName = 'cognitionIT'
	
	# Copyright statement for this module
	Copyright = '2017 cognitionIT'
	
	# Description of the functionality provided by this module
	Description = 'PowerShell Module for NITRO, the REST API service that runs on a Citrix NetScaler'
	
	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = '3.0'
	
	# Name of the Windows PowerShell host required by this module
	PowerShellHostName = ''
	
	# Minimum version of the Windows PowerShell host required by this module
	PowerShellHostVersion = ''
	
	# Minimum version of the .NET Framework required by this module
	DotNetFrameworkVersion = ''
	
	# Minimum version of the common language runtime (CLR) required by this module
	CLRVersion = ''
	
	# Processor architecture (None, X86, Amd64, IA64) required by this module
	ProcessorArchitecture = ''
	
	# Modules that must be imported into the global environment prior to importing this module
	RequiredModules = @()
	
	# Assemblies that must be loaded prior to importing this module
	RequiredAssemblies = @()
	
	# Script files () that are run in the caller's environment prior to importing this module
	ScriptsToProcess = @()
	
	# Type files (xml) to be loaded when importing this module
	TypesToProcess = @()
	
	# Format files (xml) to be loaded when importing this module
	# "xml\cognitionIT.Format.ps1xml"
	# worry about this later
	FormatsToProcess = @()
	
	# Modules to import as nested modules of the module specified in ModuleToProcess
	NestedModules = @()
	
	# Functions to export from this module
	# This is the stuff in \functions-public
	FunctionsToExport = @(
		'Clear-AcmeSqlConnectionPool',
		'Test-AcmeSqlPath'
	)
	
	# Cmdlets to export from this module
	CmdletsToExport = '*'
	
	# Variables to export from this module
	VariablesToExport = '*'
	
	# Aliases to export from this module
	# Aliases are stored in acme.psm1
	AliasesToExport = '*'
	
	# List of all modules packaged with this module
	ModuleList = @()
	
	# List of all files packaged with this module
	FileList = ''
	
	PrivateData = @{
		# PSData is module packaging and gallery metadata embedded in PrivateData
		# It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
		# We had to do this because it's the only place we're allowed to extend the manifest
		# https://connect.microsoft.com/PowerShell/feedback/details/421837
		PSData = @{
			# The primary categorization of this module (from the TechNet Gallery tech tree).
			Category = "Corporate Modules"
			
			# Keyword tags to help users find this module via navigations and search.
			Tags = @('internal','Citrix','NetScaler','NITRO','REST API')
			
			# The web address of an icon which can be used in galleries to represent this module
			IconUri = "https://acme.io/logo.png"
			
			# The web address of this module's project or support homepage.
			ProjectUri = "https://acme.io"
			
			# The web address of this module's license. Points to a page that's embeddable and linkable.
			LicenseUri = "http://www.gnu.org/licenses/gpl-3.0.en.html"
			
			# Release notes for this particular version of the module
			ReleaseNotes = "https://acme.io/releases"
			
			# If true, the LicenseUrl points to an end-user license (not just a source license) which requires the user agreement before use.
			# RequireLicenseAcceptance = ""
			
			# Indicates this is a pre-release/testing version of the module.
			IsPrerelease = 'True'
		}
	}
}
